'use client';
import {useEffect,useState} from 'react';
import {useLocation,useAppRouter,navigate} from '@/hooks/use-location';
import Link from 'next/link';
import {Menu,X} from 'lucide-react';
import {useApp} from '@/hooks/use-app';
import {Session} from '@/types';
import {Logo,SoundControls,Empty} from './ui';
import {Home} from './home';
import {Generator,Library,Reveal} from './library';
import {Workspace} from './workspace';
import {Assessment,Results} from './results';
import {Dashboard,History} from './dashboard';
import {Admin} from './admin';
import {decodeShare} from '@/lib/sharing';
import {sessionSchema} from '@/lib/storage';
import {unlockAudio} from '@/lib/sound';
export function Shell({children}:{children:React.ReactNode}){const {path}=useLocation();const router=useAppRouter();const {state,update,error}=useApp();const [menu,setMenu]=useState(false);const work=path.startsWith('/research/')||path.startsWith('/pitch/');const immersive=work&&(state.preferences.cinematic||state.preferences.recording!=='off');useEffect(()=>setMenu(false),[path]);useEffect(()=>{const click=(event:MouseEvent)=>{if(event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;const a=(event.target as HTMLElement).closest('a');if(!a||a.target||a.hasAttribute('download'))return;const url=new URL(a.href);if(url.origin!==location.origin||url.hash)return;event.preventDefault();event.stopPropagation();navigate(url.pathname+url.search);};document.addEventListener('click',click,true);if('serviceWorker' in navigator&&location.hostname!=='127.0.0.1'&&location.hostname!=='localhost')navigator.serviceWorker.register('/sw.js').then(()=>navigator.serviceWorker.ready).then(reg=>reg.active?.postMessage({type:'CACHE_ASSETS',urls:performance.getEntriesByType('resource').map(e=>e.name).filter(url=>url.startsWith(location.origin)&&/\.(js|css|woff2?)(\?|$)/.test(url))})).catch(()=>{});return()=>document.removeEventListener('click',click,true);},[]);useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,textarea,select,[contenteditable]')||e.metaKey||e.ctrlKey||e.altKey)return;if(e.key.toLowerCase()==='m'){unlockAudio();update(s=>({...s,preferences:{...s.preferences,sound:!s.preferences.sound}}));}if(e.key.toLowerCase()==='n'){e.preventDefault();router.push('/challenge');}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);},[router,update]);return <><a className="skip-link" href="#main">Skip to content</a><header className={`site-header ${work?'workspace-header':''} ${immersive?'hidden-chrome':''}`}><div className="header-inner"><Logo/><nav className={menu?'open':''} aria-label="Main navigation">{[['/','Home'],['/challenges','Challenges'],['/daily','Daily'],['/dashboard','Dashboard'],['/about','About']].map(([href,label])=><Link key={href} className={(href==='/'?path==='/':path.startsWith(href))?'active':''} href={href}>{label}</Link>)}</nav><div className="header-actions">{work?<SoundControls/>:<Link className="button primary small" href="/challenge">Start challenge <span className="shortcut">N</span></Link>}<button className="icon-button mobile-menu" aria-label={menu?'Close menu':'Open menu'} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></div></header>{error&&<div className="error global-error" role="alert">{error} <Link href="/admin">Open data management</Link></div>}<main id="main">{children}</main>{!work&&<footer className="site-footer"><Logo/><p>One subject. No preparation. Real learning.</p><div><Link href="/history">History</Link><Link href="/admin">Data management</Link><SoundControls/></div></footer>}</>;}
export function AppRoute(){const {path,query}=useLocation();const {state,ready}=useApp();const [mounted,setMounted]=useState(false);useEffect(()=>setMounted(true),[]);const [shared,setShared]=useState<Session|null>(null),[shareError,setShareError]=useState('');useEffect(()=>{if(path==='/result/shared')try{const s=sessionSchema.parse(decodeShare(location.hash.slice(1)));if(s.phase!=='complete')throw new Error('This result is incomplete.');setShared(s);}catch{setShareError('This share link is incomplete or invalid. Ask the creator for a new link.');}},[path]);
 useEffect(()=>{if(!ready)return;const s=state.sessions.find(s=>s.id===path.split('/')[2]);if(s&&['research','pitch','result'].includes(path.split('/')[1])){const phase=s.phase==='research'?'research':s.phase==='pitch'?'pitch':'result';const target=`/${phase}/${s.id}`;if(path!==target)navigate(target,true);}},[path,state.sessions,ready]);
 if(!ready||!mounted)return <div className="loading"><span className="orange">30 MINUTE</span><p>Opening your workspace…</p></div>;
 if(path==='/')return <Home/>;
 if(path==='/challenge')return <Generator/>;
 if(path==='/daily')return <Generator daily/>;
 if(path==='/challenges')return <Library initialCategory={query.get('category')||''}/>;
 if(path.startsWith('/challenges/')){const c=state.challenges.find(c=>c.slug===path.split('/')[2]);return c?<Reveal challenge={c}/>:<Empty title="Challenge not found">It may have been removed from this device’s library.</Empty>;}
 if(path==='/result/shared')return shared?<Results session={shared} shared/>:<div className="empty"><h1>{shareError||'Opening scorecard…'}</h1></div>;
 if(['/research/','/pitch/','/result/'].some(p=>path.startsWith(p))){const s=state.sessions.find(s=>s.id===path.split('/')[2]);return !s?<Empty title="Session not found on this device">Restore a full backup to recover a session from another browser.</Empty>:s.phase==='complete'?<Results session={s}/>:s.phase==='assessment'?<Assessment session={s}/>:<Workspace session={s}/>;}
 if(path==='/dashboard')return <Dashboard/>;
 if(path==='/history')return <History/>;
 if(path==='/admin')return <Admin startNew={query.get('new')==='1'}/>;
 if(path==='/about')return <About/>;
 return <Empty title="That page isn’t here.">Choose a new subject and start exploring.</Empty>;
}
function About(){return <div className="page about"><p className="eyebrow">The idea behind the clock</p><h1>The challenge<br/>is simple.</h1><div className="about-principle"><span>30</span><h2>Minutes to understand.</h2></div><div className="about-principle"><span>05</span><h2>Minutes to explain.</h2></div><div className="about-copy"><h2>One unfamiliar subject.<br/>No preparation.</h2><p>Choose a company, technology, product, or engineering system you don’t fully understand. Follow the questions. Read primary sources. Write down the model forming in your head.</p><p>When the clock hits zero, research stops. Now make it make sense to someone else, in five minutes, in your own words.</p><p>This series trains technical breadth, research speed, structured thinking, communication, product understanding, and business understanding. The score is an honest self-assessment, not a certification.</p><p>The platform gives you a timer, a structure, and starting points. The understanding has to come from you.</p><h3>Made to be used. Made to be filmed.</h3><p>Cinematic and recording modes keep the clock clear on camera, in landscape or vertical. Procedural sound marks the phases. Your result becomes a scorecard, and your takeaway becomes the seed of your next post.</p><h3>Your work stays with you.</h3><p>No account is required for the app itself. Notes and sessions are stored in this browser. Download a backup from Data management to move them between devices. Research websites need an internet connection; the local challenge workflow does not need an AI service.</p><Link className="button primary" href="/challenge">Take the challenge</Link></div></div>;}
