'use client';
import Link from 'next/link';
import {ArrowUpRight,Focus,Shuffle,Radio} from 'lucide-react';
import {useApp} from '@/hooks/use-app';
import {statistics} from '@/lib/engine';
import {ChallengeCard,SectionTitle,number} from './ui';
export function Home(){const {state}=useApp();const stats=statistics(state.sessions);const featured=state.challenges.filter(c=>c.featured).slice(0,4);return <>
<section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="orange-square"/> A tech learning & content series</p><h1><span className="orange">30 MINUTES</span><br/>TO UNDERSTAND IT.<br/><span className="outline-text">5 MINUTES</span><br/>TO PITCH IT.</h1><p className="hero-description">One unfamiliar subject. A running clock.<br/>Research under pressure. Then explain what you learned before the time runs out.</p><div className="actions"><Link href="/challenge" className="button primary"><Shuffle size={17}/> Start challenge</Link><Link href="/challenges" className="button">Browse case studies</Link></div><div className="hero-footnote"><span>No preparation.</span><span>No generated answers.</span><span>Real learning.</span></div></div>
<div className="hero-instrument"><div className="instrument-top"><span className="mono">THE RESEARCH WINDOW</span><Focus size={18}/></div><div className="instrument-body"><div className="time-ruler">{Array.from({length:31},(_,i)=><i key={i} className={i%5===0?'major':''}/>)}</div><div className="hero-timer">30<span>:</span>00</div><div className="instrument-status"><span><i className="orange-dot"/> READY WHEN YOU ARE</span><span>1800 SECONDS</span></div><div className="instrument-rule"/><div className="phase-legend"><div><span className="phase-index">01</span><strong>Find the signal.</strong><p>Research. Connect. Question.</p></div><div><span className="phase-index">02</span><strong>Make it make sense.</strong><p>Five minutes. Your own words.</p></div></div></div><div className="instrument-bottom"><span className="mono">ONE SUBJECT. ZERO EXCUSES.</span><span className="instrument-cross">+</span></div></div></section>
<div className="stats-strip">{[[state.challenges.length,'Challenges to explore'],[stats.complete.length,'Challenges completed'],[stats.streak,'Day streak'],[stats.complete.length?stats.averageScore.toFixed(1):'—','Average self score']].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div>
<section className="section"><SectionTitle label="Choose your next rabbit hole" title="Featured challenges"><Link className="text-link" href="/challenges">View the library <ArrowUpRight size={16}/></Link></SectionTitle><div className="card-grid">{featured.map(c=><ChallengeCard key={c.id} challenge={c}/>)}</div></section>
<section className="section process-section"><SectionTitle label="The format" title="35 minutes. A different perspective."/><div className="process-grid">{[['01','Get the challenge','Go somewhere unfamiliar.'],['02','Research for 30','Follow sources. Build a model.'],['03','Clock hits zero','Close the tabs. Gather your thoughts.'],['04','Pitch for 5','Explain it in your own words.'],['05','Reflect + score','Find what stuck. Find the gaps.']].map(([n,t,d])=><div key={n}><span className="process-number">{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section className="section"><SectionTitle label="Explore the field" title="Curiosity has no department."/><div className="category-grid">{[...new Set(state.challenges.map(c=>c.category))].map((cat,i)=><Link key={cat} href={`/challenges?category=${encodeURIComponent(cat)}`}><span className="mono muted">{number(i+1)}</span><strong>{cat}</strong><span className="mono">{state.challenges.filter(c=>c.category===cat).length}</span><ArrowUpRight size={16}/></Link>)}</div></section>
{stats.complete.length>0&&<section className="section"><SectionTitle title="Your recent fieldwork"><Link href="/history" className="text-link">View history</Link></SectionTitle>{stats.complete.slice(0,3).map(s=><Link className="history-row" key={s.id} href={`/result/${s.id}`}><span className="mono muted">#{number(s.number)}</span><strong>{s.challenge.title}</strong><span>{s.challenge.category}</span><span>{s.scores.reduce((a,b)=>a+b,0)/8}/10</span></Link>)}</section>}
<section className="closing"><div><p className="eyebrow">Built for curious people</p><h2>The challenge is simple.<br/>The understanding is earned.</h2><p>Train technical breadth, research speed, and the ability to make complex ideas clear. Film the process. Share what you actually learned.</p><Link href="/about" className="text-link">About the series <ArrowUpRight size={16}/></Link></div><div className="closing-cta"><Radio/><h3>Your next episode<br/>starts here.</h3><Link className="button primary" href="/challenge">Start challenge</Link></div></section>
</>;}
