'use client';
import Link from 'next/link';
import {ArrowUpRight,Clock3,Command,Volume2,VolumeX,X} from 'lucide-react';
import {useApp} from '@/hooks/use-app';
import {Challenge,Session} from '@/types';
import {formatTime,remaining,statusFor} from '@/lib/engine';
import {unlockAudio} from '@/lib/sound';
import {ReactNode,useEffect,useRef} from 'react';
export const number=(n:number)=>String(n).padStart(3,'0');
export function Logo(){return <Link className="logo" href="/" aria-label="30 Minute home"><span className="logo-mark"><i/><i/><i/></span><strong>30<span>MINUTE</span></strong></Link>;}
export function Badge({children}:{children:ReactNode}){return <span className="badge">{children}</span>;}
export function SoundControls(){const {state,update,play}=useApp();const p=state.preferences;return <div className="sound-controls"><button className="quiet" onClick={()=>{unlockAudio();update(s=>({...s,preferences:{...s.preferences,sound:!p.sound}}));play('click');}} aria-label={p.sound?'Mute sound':'Enable sound'}>{p.sound?<Volume2 size={16}/>:<VolumeX size={16}/>}<span>Sound {p.sound?'on':'off'}</span></button><label className="volume"><span className="sr-only">Master volume</span><input type="range" min="0" max="1" step=".05" value={p.volume} onChange={e=>update(s=>({...s,preferences:{...s.preferences,volume:Number(e.target.value)}}))}/></label></div>;}
export function ChallengeCard({challenge:c}:{challenge:Challenge}){const {state}=useApp();const status=statusFor(c,state);return <Link href={`/challenges/${c.slug}`} className="challenge-card"><div className="row between"><span className="mono muted">CASE / {number(c.number)}</span><ArrowUpRight size={17}/></div><div className="topic-symbol" aria-hidden="true">{c.title==='Perplexity'?<Command/>:c.title==='Docker'?<span>▤</span>:c.title==='Netflix'?<b>N</b>:<span>{c.title.slice(0,2)}</span>}</div><h3>{c.title}</h3><p className="card-category">{c.category}</p><p className="card-description">{c.description}</p><div className="row between card-bottom"><Badge>{c.difficulty}</Badge><span className="mono muted status">{status==='Untouched'?c.type:status}</span></div></Link>;}
export function SourceList({challenge}:{challenge:Challenge}){return <div className="source-list">{challenge.sources.length?challenge.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noopener noreferrer"><div><strong>{s.label}</strong><span>{new URL(s.url).hostname}</span></div><ArrowUpRight size={18}/></a>):<p className="muted">No sources added. Start with the subject’s official website.</p>}<p className="hint">Starting points for your research. Check the date, follow the evidence, form your own view.</p></div>;}
export function Timer({session,large=false}:{session:Session;large?:boolean}){const {now}=useApp();const seconds=remaining(session,now);const duration=session.phase==='research'?1800:300;return <div className={`timer-block ${large?'large':''} ${seconds<=60?'urgent':''}`}><div className="row between mono"><span>{session.phase==='research'?'Research time':'Pitch time'}</span><span className="timer-state">{session.pausedAt?'Paused':<><i className="live-dot"/> In progress</>}</span></div><div className="timer" role="timer" aria-label={`${formatTime(seconds)} remaining`}>{formatTime(seconds)}</div><progress value={seconds} max={duration} aria-label="Time remaining"/><div className="row between timer-caption"><span>{session.practice?'Practice session':'The clock is running.'}</span><span>{session.phase==='research'?'30 minutes. One subject.':'Make every word count.'}</span></div></div>;}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();const el=ref.current;return()=>el?.close();},[]);return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="row between"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X/></button></div>{children}</dialog>;}
export function Empty({title,children}:{title:string;children:ReactNode}){return <div className="empty"><Clock3/><h2>{title}</h2><p>{children}</p><Link className="button primary" href="/challenge">Start a challenge</Link></div>;}
export function SectionTitle({label,title,children}:{label?:string;title:string;children?:ReactNode}){return <div className="section-heading"><div>{label&&<p className="eyebrow">{label}</p>}<h2>{title}</h2></div>{children}</div>;}
