'use client';
import {useEffect,useState} from 'react';
import {useAppRouter} from '@/hooks/use-location';
import {BookOpen,CheckCheck,FileText,Maximize2,Pause,Play,Video,Minimize2} from 'lucide-react';
import {useApp} from '@/hooks/use-app';
import {Session,sections} from '@/types';
import {advance,pause,remaining} from '@/lib/engine';
import {Badge,Modal,SourceList,Timer,number} from './ui';
const prompts=['What problem does it solve? Who experiences it? Why does it matter?','How does someone use it? What is the core workflow?','What makes it work? Explain the important technical choices.','Sketch the components, data flow, and dependencies in words.','Who pays, what do they pay for, and what does it cost to deliver?','What alternatives exist, and how do they differ?','What is difficult to replicate? What compounds over time?','What can fail? Which tradeoffs and limitations matter?','What surprised you? What is your own interpretation?','Shape your own explanation: problem, solution, technology, business, verdict.'];
const checkLabels=['I understand the problem','I understand the product','I understand the technology','I understand the architecture','I understand the business model','I know the competitors','I understand the moat','I understand the weaknesses','I have formed my own opinion','I can explain it in 5 minutes'];
export function Workspace({session:s}:{session:Session}){const {state,update,editSession,play,now}=useApp();const router=useAppRouter();const [tab,setTab]=useState('Problem'),[panel,setPanel]=useState('notes'),[end,setEnd]=useState(false);const p=state.preferences;const pitch=s.phase==='pitch';const left=remaining(s,now);const checked=s.checklist.filter(Boolean).length;
 useEffect(()=>{const target=s.phase==='research'?'research':s.phase==='pitch'?'pitch':'result';router.replace(`/${target}/${s.id}`);},[s.phase,s.id,router]);
 const setPrefs=(partial:Partial<typeof p>)=>update(st=>({...st,preferences:{...st.preferences,...partial}}));
 const cinematic=()=>{setPrefs({cinematic:!p.cinematic});if(!p.cinematic)document.documentElement.requestFullscreen?.().catch(()=>{});else if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});};
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,textarea,select,[contenteditable]')||e.metaKey||e.ctrlKey||e.altKey)return;if(e.code==='Space'){e.preventDefault();editSession(s.id,x=>pause(advance(x)));}if(e.key.toLowerCase()==='f'){e.preventDefault();cinematic();}if(e.key==='Escape'){setPrefs({cinematic:false,recording:'off'});}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);});
 if(s.phase!=='research'&&s.phase!=='pitch')return null;
 const noteKey=pitch?'Pitch Notes':tab;
 return <div className={`workspace ${p.cinematic?'cinematic':''} ${p.recording!=='off'?'recording '+p.recording:''}`}><div className="workspace-toolbar"><span className="mono muted">Challenge <span className="orange">/</span> {pitch?'Pitch':'Research'}</span><div className="row"><button className="quiet" onClick={cinematic}>{p.cinematic?<Minimize2 size={16}/>:<Maximize2 size={16}/>} Cinematic</button><label className="record-select"><Video size={16}/><span className="sr-only">Recording layout</span><select value={p.recording} onChange={e=>setPrefs({recording:e.target.value as typeof p.recording})}><option value="off">Recording off</option><option value="wide">Recording 16:9</option><option value="vertical">Recording 9:16</option></select></label><button className="quiet" onClick={()=>editSession(s.id,x=>pause(advance(x)))}>{s.pausedAt?<Play size={16}/>:<Pause size={16}/>} {s.pausedAt?'Resume':'Pause'}</button><button className="button small danger" onClick={()=>setEnd(true)}>{pitch?'Finish pitch':'End research'}</button></div></div>
 <div className="workspace-heading"><div><p className="eyebrow">{pitch?'Research complete':`Challenge #${number(s.challenge.number)}`}<span className="test-number">TEST / {number(s.number)}</span></p><h1>{pitch?'Your 5 minute pitch starts now.':s.challenge.title}</h1><div className="row"><span className="mono">{pitch?s.challenge.title:s.challenge.category}</span><Badge>{s.challenge.difficulty}</Badge></div>{!pitch&&<p className="workspace-description">{s.challenge.description}</p>}</div><Timer session={s} large={pitch||p.cinematic||p.recording!=='off'}/></div>
 {left<=60&&<p className="time-warning" role="status">{left<=30?'30 seconds or less.':'Final minute.'} {pitch?'Land your key insight.':'Pull your pitch notes together.'}</p>}{s.pausedAt&&<p className="notice" role="status">Timer paused. This attempt is marked as practice.</p>}
 <div className="recording-essentials"><p className="eyebrow">{pitch?'Pitch mode':'Research mode'}</p><h2>{s.challenge.title}</h2><p>{pitch?'Problem / Solution / Technology / Business / Your verdict':s.challenge.description}</p><div className="record-notes">{s.notes['Pitch Notes']||'Your own understanding. Your own words.'}</div></div>
 <div className={`work-grid ${pitch?'pitch-grid':''}`}>
 {!pitch&&<aside className="work-nav"><div className="work-switch"><button className={panel==='notes'?'active':''} onClick={()=>setPanel('notes')}><FileText size={16}/> Research</button><button className={panel==='sources'?'active':''} onClick={()=>setPanel('sources')}><BookOpen size={16}/> Sources</button><button className={panel==='checklist'?'active':''} onClick={()=>setPanel('checklist')}><CheckCheck size={16}/> Checklist</button></div><nav aria-label="Research sections">{sections.map((sec,i)=><button key={sec} className={tab===sec&&panel==='notes'?'active':''} onClick={()=>{setTab(sec);setPanel('notes');}}><span className="mono">{String(i+1).padStart(2,'0')}</span>{sec}{s.notes[sec]&&<i className="note-dot"/>}</button>)}</nav></aside>}
 <section className="editor-panel">{pitch?<div className="pitch-objectives"><p className="eyebrow">Seven beats. One clear explanation.</p>{['Problem','Solution','How it works','Technology','Business','Competition','Your verdict / insight'].map((t,i)=><div key={t}><span className="mono">{String(i+1).padStart(2,'0')}</span><strong>{t}</strong></div>)}</div>:panel==='sources'?<><h2>Research sources</h2><SourceList challenge={s.challenge}/><h3>Your research questions</h3><ul className="question-list">{s.challenge.researchQuestions.map(q=><li key={q}>{q}</li>)}</ul></>:panel==='checklist'?<Checklist session={s}/>:<><div className="row between"><h2>{tab}</h2><span className="saved"><i/> Saved on this device</span></div><p className="editor-prompt">{prompts[sections.indexOf(tab as typeof sections[number])]}</p><label className="sr-only" htmlFor="research-note">{tab} notes</label><textarea id="research-note" className="research-textarea" value={s.notes[tab]||''} placeholder="Start with a question. Follow it somewhere interesting…" onChange={e=>editSession(s.id,x=>({...x,notes:{...x.notes,[tab]:e.target.value}}))}/><div className="editor-footer"><span>{(s.notes[tab]||'').trim().split(/\s+/).filter(Boolean).length} words</span><span>Your notes. Your understanding.</span></div></>}</section>
 <aside className="research-side">{pitch?<><div className="row between"><h3>Pitch notes</h3><span className="saved"><i/> Autosaved</span></div><label className="sr-only" htmlFor="pitch-note">Pitch notes</label><textarea id="pitch-note" className="pitch-textarea" value={s.notes[noteKey]||''} placeholder="Your own talking points…" onChange={e=>editSession(s.id,x=>({...x,notes:{...x.notes,[noteKey]:e.target.value}}))}/><details><summary>Review your research notes</summary>{sections.filter(sec=>sec!=='Pitch Notes'&&s.notes[sec]).map(sec=><div className="read-note" key={sec}><h4>{sec}</h4><p>{s.notes[sec]}</p></div>)}</details></>:<><Checklist session={s}/><div className="side-source"><h3>Starting sources</h3><SourceList challenge={s.challenge}/></div></>}</aside></div>
 <div className="workspace-bottom"><span className="mono">{pitch?'05':'30'} MINUTE / {pitch?'PITCH':'RESEARCH'} SESSION</span><span>Space: pause <kbd>M</kbd> sound <kbd>F</kbd> cinematic <kbd>Esc</kbd> exit</span><span>{checked}/10 understood</span></div>
 {end&&<Modal title={pitch?'Finish your pitch early?':'End research and begin your pitch?'} onClose={()=>setEnd(false)}><p>{pitch?'Your actual pitch time will be recorded. You’ll move to reflection and self-assessment.':'Your five-minute pitch starts immediately. Your notes stay available, and your actual research time is recorded.'}</p><div className="actions"><button className="button" onClick={()=>setEnd(false)}>Keep going</button><button className="button primary" onClick={()=>{editSession(s.id,x=>advance(x,Date.now(),true));play(pitch?'pitch-complete':'transition');setEnd(false);}}>{pitch?'Finish and reflect':'Start 05:00 pitch'}</button></div></Modal>}
 </div>;
}
export function Checklist({session:s}:{session:Session}){const {editSession,play}=useApp();const n=s.checklist.filter(Boolean).length;return <div className="checklist"><div className="row between"><h3>Research checklist</h3><span className="mono muted">{n}/10</span></div><progress value={n} max={10} aria-label="Research checklist completion"/>{checkLabels.map((label,i)=><label key={label}><input type="checkbox" checked={s.checklist[i]} onChange={e=>{editSession(s.id,x=>({...x,checklist:x.checklist.map((v,j)=>j===i?e.target.checked:v)}));if(e.target.checked)play('check');}}/><span>{label}</span></label>)}</div>;}
